services:

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

  # nextjs:
  #   container_name: nextfront  # the name of the container
  #   image: nextapp  # the name of the Docker image
  #   build:
  #     context: .  # build the Dockerfile in the current directory
  #     dockerfile: Dockerfile  # the name of the Dockerfile
  #   ports:
  #     - "3000:3000"  # expose the container's port 3000 to the host's port 3000
  #   env_file:
  #     - .env  # load environment variables from the .env file
  #   restart: always  # restart the container always
  #   volumes:
  #     - .:/app  # mount the current directory to the /app directory in the container

  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     - postgres

volumes:
  postgres-data: